name = "server"
main = "src/index.ts"
compatibility_date = "2023-04-06"

persist = true
local = true
kv_namespaces = [
  { binding = "KV", id = "da599854f99542e3aa7a4c8089bc05f9", preview_id = "da599854f99542e3aa7a4c8089bc05f9" },
]


[[ d1_databases ]]
binding = "d1"
database_name = "scify-db"
database_id = "62851ee0-dc59-40a3-a721-8d6621f3056f"
migrations_dir = "./drizzle"
local = true
